In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import mean_absolute_error, mean_squared_error
import math

In [ ]:
df1 = pd.read_csv("drug.csv")
df2 = pd.read_csv("iris.csv")
df3 = pd.read_csv("petrol_consumption.csv")


In [ ]:
print(df1.info())
print(df2.info())
print(df3.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
<class 'pandas.core.frame.DataF

In [ ]:
X_iris = df2.drop("species", axis=1)
y_iris = df2["species"]

X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

iris_model = DecisionTreeClassifier()
iris_model.fit(X_train, y_train)

y_pred = iris_model.predict(X_test)

print("IRIS Accuracy:", accuracy_score(y_test, y_pred))
print("IRIS Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

IRIS Accuracy: 1.0
IRIS Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:

le = LabelEncoder()

df1["Sex"] = le.fit_transform(df1["Sex"])
df1["BP"] = le.fit_transform(df1["BP"])
df1["Cholesterol"] = le.fit_transform(df1["Cholesterol"])
df1["Drug"] = le.fit_transform(df1["Drug"])

X_drug = df1.drop("Drug", axis=1)
y_drug = df1["Drug"]

X_train, X_test, y_train, y_test = train_test_split(X_drug, y_drug, test_size=0.2, random_state=42)

drug_model = DecisionTreeClassifier()
drug_model.fit(X_train, y_train)

y_pred = drug_model.predict(X_test)

print("\nDrug Dataset Accuracy:", accuracy_score(y_test, y_pred))
print("Drug Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Drug Dataset Accuracy: 1.0
Drug Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [ ]:
X = df3.drop("Petrol_Consumption", axis=1)
y = df3["Petrol_Consumption"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

reg_model = DecisionTreeRegressor()
reg_model.fit(X_train, y_train)

y_pred = reg_model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = math.sqrt(mse)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 85.4
Mean Squared Error: 16576.8
Root Mean Squared Error: 128.75092232679344
